root: true
parser: '@typescript-eslint/parser'
env:
  es6: true
  browser: true
  node: true
plugins:
  - '@typescript-eslint'
  - 'svelte3'
overrides:
  - files:
      - '**/*.svelte'
    processor: 'svelte3/svelte3'
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:@typescript-eslint/recommended'
rules:
  '@typescript-eslint/no-var-requires': off
